version: "3.9"

services:

  db:
    image: postgres:16-alpine
    container_name: bankRest-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bankRest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bankRest"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bankRest-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bankRest
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data: